from pathlib import Path

path = Path("PENDING_REVIEWED_COMPONENTS.md")
text = path.read_text()

old = "- Deferred review: the deliberate copy-owning `as_points()` input contract versus an optional future zero-copy mode remains a separate API question. Chunked spline output was intentionally not introduced in this optimization pass.\n- Archive note: reviewed smoothing behavior, initialization, cached output-only resampling, current non-chunked memory optimizations, NumPy 2.x conversion semantics, and result mutability protection are validated; the remaining zero-copy input question can be explicitly deferred before formal archival.\n"
new = "- Accepted input-ownership design: `as_points()` intentionally copies validated input coordinates so `SmoothedLine.raw_coords` is isolated from caller-side mutation. A zero-copy input mode is intentionally not supported because its aliasing risk outweighs the retained-input memory saving for the current API. Chunked spline output was intentionally not introduced in this optimization pass.\n- Archive note: reviewed smoothing behavior, initialization, cached output-only resampling, current non-chunked memory optimizations, NumPy 2.x conversion semantics, result mutability protection, and input ownership are validated; remaining review work should focus on adjacent components rather than reopening zero-copy input semantics.\n"
if old not in text:
    raise RuntimeError("SmoothedLine deferred-review block not found")
text = text.replace(old, new, 1)

section = '''\n### `SmoothedLineFunc`\n\n- Source: `src/nematics3d/classes/smoothed_line.py`.\n- Status: review started; the first performance/memory cleanup removes the full pairwise sample-delta matrix from `linefunc_smooth_values()` without changing the local polynomial smoothing mathematics.\n- Performance/memory cleanup: the previous implementation materialized `_linefunc_sample_delta_matrix(u_samples, mode)`, an `N x N` float array, before iterating row by row. The smoothing loop now computes only the current length-`N` delta vector as `u_samples - u_center`; wrap mode applies the same `[-50, 50)` periodic remapping in place. The obsolete `_linefunc_sample_delta_matrix()` helper was removed. Peak delta-storage complexity therefore drops from `O(N^2)` to `O(N)` while arithmetic complexity remains `O(N^2)` at this stage.\n- Behavior reviewed so far: streamed deltas are numerically identical to the former full-matrix deltas for both `interp` and periodic `wrap` modes; scalar and vector-valued smoothing retain the existing weighted local-polynomial behavior.\n- Focused tests: `tests/smooth/test_smoothed_line_func.py`, currently two regression tests comparing the streamed implementation against a test-local reference implementation of the former full-matrix algorithm for nonuniform `interp`/vector data and `wrap`/scalar data.\n- Validation actually run: GitHub Actions run `33337186451`, job `99326086983`, Ubuntu 24.04 / Python 3.12, reported `12 passed in 0.97s` across the ten existing `SmoothedLine` tests plus the two new `SmoothedLineFunc` regression tests; `py_compile`, Black formatting/checks, and a final `git grep` confirming removal of `_linefunc_sample_delta_matrix` also passed.\n- Review commit: `db2ca8cb4753e442cfffb6cafd5df7d0d926bd09` (`Stream SmoothedLineFunc sample deltas`).\n- Tutorial: not evaluated yet; this component is still under active review.\n- Archive note: not ready for formal archival. Initialization/assignment plumbing, sample-validation semantics, owner-option invalidation boundaries, output mutability, and further local-window performance opportunities still need review.\n'''

if "### `SmoothedLineFunc`" in text:
    raise RuntimeError("SmoothedLineFunc pending section already exists")
text = text.rstrip() + "\n" + section
path.write_text(text)
