"""Generate the shared synthetic vesicle Q-field used by workflow tutorials.

The goal is not to reproduce any particular experiment.  Instead, this script
creates a compact, fully reproducible 3-D nematic field with several features
that commonly appear in reconstructed experimental data:

* an approximately spherical vesicle;
* different director textures inside and outside the vesicle;
* imperfect tangential anchoring near the *inner* vesicle surface;
* four +/- 1/2 disclination lines inside the vesicle;
* medium-scale distortions and voxel-scale Q noise.

Two defect lines pass close to the vesicle centre and therefore span almost
the full diameter.  A third is a shorter peripheral chord, while the fourth
is a closed disclination loop.  Their centreline positions are saved as
ground truth.

The Q tensor is saved in Nematics3D's five-component convention:

    [Q_xx, Q_xy, Q_xz, Q_yy, Q_yz]

with Q_zz = -Q_xx - Q_yy.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


DEFAULT_SHAPE = (72, 72, 72)
DEFAULT_SEED = 240517


def _normalize(v: np.ndarray, *, eps: float = 1e-12) -> np.ndarray:
    norm = np.linalg.norm(v, axis=-1, keepdims=True)
    return v / np.maximum(norm, eps)


def _smoothstep01(x: np.ndarray) -> np.ndarray:
    x = np.clip(x, 0.0, 1.0)
    return x * x * (3.0 - 2.0 * x)


def _q5_from_n_s(n: np.ndarray, s: np.ndarray) -> np.ndarray:
    nx, ny, nz = np.moveaxis(n, -1, 0)
    one_third = np.float32(1.0 / 3.0)
    q = np.empty(n.shape[:-1] + (5,), dtype=np.float32)
    q[..., 0] = s * (nx * nx - one_third)
    q[..., 1] = s * nx * ny
    q[..., 2] = s * nx * nz
    q[..., 3] = s * (ny * ny - one_third)
    q[..., 4] = s * ny * nz
    return q


def _build_grid(shape: tuple[int, int, int]) -> tuple[np.ndarray, ...]:
    axes = [
        np.linspace(-1.0, 1.0, n, dtype=np.float32)
        for n in shape
    ]
    return np.meshgrid(*axes, indexing="ij")


def _spanning_defect_geometry(
    x: np.ndarray,
) -> tuple[list[dict[str, float]], list[tuple[np.ndarray, np.ndarray]]]:
    """Return metadata and centreline coordinates for x-like defect lines.

    All four lines are predominantly parallel to x.  This makes a clean
    half-integer winding construction possible while still allowing gentle
    curvature through y(x) and z(x).
    """

    specs = [
        # Two central, long spanning lines.
        {"name": "span_A", "charge_2s": +1, "y0": -0.18, "z0": -0.12, "wiggle": 0.035, "phase": 0.2},
        {"name": "span_B", "charge_2s": -1, "y0": +0.20, "z0": +0.13, "wiggle": 0.030, "phase": 1.5},
        # One peripheral line.  Its offset makes the in-vesicle chord shorter.
        {"name": "edge_C", "charge_2s": +1, "y0": +0.55, "z0": -0.36, "wiggle": 0.020, "phase": 2.4},
    ]

    centres: list[tuple[np.ndarray, np.ndarray]] = []
    for spec in specs:
        phase = float(spec["phase"])
        amp = float(spec["wiggle"])
        y_c = float(spec["y0"]) + amp * np.sin(2.2 * np.pi * x + phase)
        z_c = float(spec["z0"]) + 0.8 * amp * np.sin(1.7 * np.pi * x + 0.7 * phase)
        centres.append((y_c.astype(np.float32), z_c.astype(np.float32)))
    return specs, centres


def _loop_geometry(
    x: np.ndarray,
    y: np.ndarray,
    z: np.ndarray,
) -> tuple[dict[str, float], np.ndarray, np.ndarray]:
    """Return phase and core distance for a circular disclination loop.

    The loop lies in the xy plane.  In toroidal coordinates the local polar
    angle around the ring core is atan2(z-z0, r_xy-R), so half of this angle
    constructs a +/-1/2 nematic disclination around the entire closed ring.
    """

    spec = {
        "name": "loop_D",
        "charge_2s": -1,
        "x0": 0.08,
        "y0": -0.08,
        "z0": 0.22,
        "radius": 0.19,
    }
    dx = x - float(spec["x0"])
    dy = y - float(spec["y0"])
    dz = z - float(spec["z0"])
    radial = np.sqrt(dx * dx + dy * dy)
    radial_offset = radial - float(spec["radius"])
    phase = np.arctan2(dz, radial_offset)
    distance = np.sqrt(radial_offset * radial_offset + dz * dz)
    return spec, phase, distance


def generate_synthetic_vesicle(
    shape: tuple[int, int, int] = DEFAULT_SHAPE,
    *,
    seed: int = DEFAULT_SEED,
) -> dict[str, object]:
    """Create the synthetic field and return arrays plus metadata."""

    rng = np.random.default_rng(seed)
    x, y, z = _build_grid(shape)

    # A mildly non-spherical vesicle prevents the interface from looking like
    # a perfect analytic toy while keeping the geometry easy to understand.
    x_s = x / 0.91
    y_s = y / 0.84
    z_s = z / 0.88
    rho = np.sqrt(x_s * x_s + y_s * y_s + z_s * z_s)
    radius = 0.72
    signed_distance = rho - radius
    mask = rho <= radius

    # Four +/-1/2 lines are generated by adding half of the polar angle around
    # each x-oriented centreline to the nematic phase.  Because n == -n, a pi
    # rotation of n around the core is a genuine half-integer disclination.
    line_specs, centres = _spanning_defect_geometry(x)
    theta = (
        0.18
        + 0.12 * np.sin(1.6 * np.pi * x)
        + 0.08 * np.cos(1.3 * np.pi * z)
    )
    core_distances: list[np.ndarray] = []
    for spec, (y_c, z_c) in zip(line_specs, centres):
        dy = y - y_c
        dz = z - z_c
        phi = np.arctan2(dz, dy)
        theta = theta + 0.5 * float(spec["charge_2s"]) * phi
        core_distances.append(np.sqrt(dy * dy + dz * dz))

    loop_spec, loop_phase, loop_distance = _loop_geometry(x, y, z)
    theta = theta + 0.5 * float(loop_spec["charge_2s"]) * loop_phase
    core_distances.append(loop_distance)

    # Interior director: mostly in the yz plane, with a modest x component so
    # the field is fully three-dimensional rather than a stack of 2-D slices.
    n_inside = np.stack(
        [
            0.22 + 0.08 * np.sin(2.0 * np.pi * y + 0.7 * z),
            np.cos(theta),
            np.sin(theta),
        ],
        axis=-1,
    )
    n_inside = _normalize(n_inside)

    # Approximate outward normal of the ellipsoidal vesicle.  In an inner
    # shell we project the director onto the local tangent plane, then blend
    # only partially toward that projection to make anchoring imperfect.
    surface_normal = _normalize(
        np.stack(
            [x / (0.91 * 0.91), y / (0.84 * 0.84), z / (0.88 * 0.88)],
            axis=-1,
        )
    )
    normal_component = np.sum(n_inside * surface_normal, axis=-1, keepdims=True)
    tangent = _normalize(n_inside - normal_component * surface_normal)

    inner_shell_width = 0.12
    shell_coord = (rho - (radius - inner_shell_width)) / inner_shell_width
    anchor_weight = 0.78 * _smoothstep01(shell_coord)
    anchor_weight *= mask
    n_inside = _normalize(
        (1.0 - anchor_weight[..., None]) * n_inside
        + anchor_weight[..., None] * tangent
    )

    # Exterior texture is deliberately quite different: approximately z-like
    # with a slow twist.  A narrow transition layer keeps Q finite while still
    # leaving a clear inside/outside contrast.
    n_outside = np.stack(
        [
            0.26 * np.cos(1.4 * np.pi * y),
            0.18 * np.sin(1.2 * np.pi * x + 0.4),
            np.ones_like(x),
        ],
        axis=-1,
    )
    n_outside = _normalize(n_outside)

    transition_width = 0.045
    inside_weight = 0.5 * (1.0 - np.tanh(signed_distance / transition_width))
    n = _normalize(
        inside_weight[..., None] * n_inside
        + (1.0 - inside_weight[..., None]) * n_outside
    )

    # Scalar order is lower at the interface and strongly suppressed in the
    # defect cores.  The four line cores are multiplied together so each line
    # has a genuine low-order tube coincident with its phase singularity.
    s = np.where(mask, 0.72, 0.62).astype(np.float32)
    s *= 1.0 - 0.18 * np.exp(-(signed_distance / 0.055) ** 2)
    core_width = 0.028
    for distance in core_distances:
        s *= 1.0 - 0.94 * np.exp(-((distance / core_width) ** 2)) * mask
    s = np.clip(s, 0.025, None).astype(np.float32)

    q_clean = _q5_from_n_s(n, s)

    # Add reproducible experimental-style roughness directly in Q space.  A
    # low-frequency trigonometric component creates coherent distortions and
    # Gaussian voxel noise leaves something useful for smoothing tutorials.
    medium = (
        np.sin(2.7 * np.pi * x + 0.6 * y)
        + 0.65 * np.cos(2.2 * np.pi * y - 0.4 * z)
        + 0.45 * np.sin(1.9 * np.pi * z + 0.5 * x)
    ).astype(np.float32)
    medium /= np.max(np.abs(medium))

    q = q_clean.copy()
    component_scale = np.array([0.018, 0.015, 0.015, 0.018, 0.015], dtype=np.float32)
    spatial_weights = np.array([1.0, -0.7, 0.55, -0.8, 0.65], dtype=np.float32)
    q += medium[..., None] * component_scale * spatial_weights
    q += rng.normal(0.0, component_scale, size=q.shape).astype(np.float32)

    # Ground-truth centrelines are sampled only where they lie inside the
    # vesicle.  This naturally makes peripheral defects shorter chords.
    x_line = np.linspace(-1.0, 1.0, 401, dtype=np.float32)
    x3 = x_line[:, None, None]
    sampled_specs, line_centres = _spanning_defect_geometry(x3)
    line_points: dict[str, np.ndarray] = {}
    for spec, (y_c, z_c) in zip(sampled_specs, line_centres):
        y1 = np.asarray(y_c[:, 0, 0], dtype=np.float32)
        z1 = np.asarray(z_c[:, 0, 0], dtype=np.float32)
        rho_line = np.sqrt(
            (x_line / 0.91) ** 2 + (y1 / 0.84) ** 2 + (z1 / 0.88) ** 2
        )
        keep = rho_line <= radius
        line_points[str(spec["name"])] = np.column_stack([x_line[keep], y1[keep], z1[keep]])

    loop_t = np.linspace(0.0, 2.0 * np.pi, 401, endpoint=True, dtype=np.float32)
    loop_points = np.column_stack(
        [
            float(loop_spec["x0"]) + float(loop_spec["radius"]) * np.cos(loop_t),
            float(loop_spec["y0"]) + float(loop_spec["radius"]) * np.sin(loop_t),
            np.full_like(loop_t, float(loop_spec["z0"])),
        ]
    ).astype(np.float32)
    line_points[str(loop_spec["name"])] = loop_points

    all_specs = [*line_specs, loop_spec]

    metadata = {
        "description": "Synthetic vesicle-like 3-D nematic Q field for Nematics3D workflow tutorials.",
        "provenance": "Fully synthetic; generated analytically and with seeded random noise. No experimental data are copied.",
        "shape_xyz": list(shape),
        "coordinate_extent": [[-1.0, 1.0], [-1.0, 1.0], [-1.0, 1.0]],
        "q_component_order": ["Q_xx", "Q_xy", "Q_xz", "Q_yy", "Q_yz"],
        "random_seed": int(seed),
        "vesicle": {
            "ellipsoid_axis_scales": [0.91, 0.84, 0.88],
            "levelset_radius": radius,
            "inner_tangential_anchoring_strength": 0.78,
            "inner_anchoring_shell_width": inner_shell_width,
            "inside_outside_transition_width": transition_width,
        },
        "defects": [
            {
                "name": str(spec["name"]),
                "nematic_charge": 0.5 * int(spec["charge_2s"]),
                "nominal_y0": float(spec["y0"]),
                "nominal_z0": float(spec["z0"]),
                "ground_truth_points": int(line_points[str(spec["name"])].shape[0]),
            }
            for spec in all_specs
        ],
        "roughness": {
            "medium_scale_q_amplitude": component_scale.tolist(),
            "voxel_noise_std_per_q_component": component_scale.tolist(),
        },
    }

    return {
        "Q": q,
        "Q_clean": q_clean,
        "director_ground_truth": n.astype(np.float32),
        "S_ground_truth": s,
        "mask_vesicle": mask.astype(np.uint8),
        "defect_lines": line_points,
        "metadata": metadata,
    }


def write_dataset(
    output_dir: Path,
    *,
    shape: tuple[int, int, int] = DEFAULT_SHAPE,
    seed: int = DEFAULT_SEED,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    data = generate_synthetic_vesicle(shape=shape, seed=seed)

    np.save(output_dir / "Q.npy", data["Q"])
    np.save(output_dir / "Q_clean_ground_truth.npy", data["Q_clean"])
    np.save(output_dir / "director_ground_truth.npy", data["director_ground_truth"])
    np.save(output_dir / "S_ground_truth.npy", data["S_ground_truth"])
    np.save(output_dir / "mask_vesicle.npy", data["mask_vesicle"])
    np.savez_compressed(output_dir / "defect_lines_ground_truth.npz", **data["defect_lines"])
    (output_dir / "metadata.json").write_text(
        json.dumps(data["metadata"], indent=2) + "\n",
        encoding="utf-8",
    )


def _parse_shape(text: str) -> tuple[int, int, int]:
    values = tuple(int(v.strip()) for v in text.split(","))
    if len(values) != 3 or any(v < 16 for v in values):
        raise argparse.ArgumentTypeError("shape must be Nx,Ny,Nz with every N >= 16")
    return values


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--shape",
        type=_parse_shape,
        default=DEFAULT_SHAPE,
        help="Grid shape as Nx,Ny,Nz (default: 72,72,72).",
    )
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "data" / "synthetic_vesicle",
    )
    args = parser.parse_args()

    write_dataset(args.output_dir, shape=args.shape, seed=args.seed)
    print(f"Synthetic vesicle dataset written to: {args.output_dir}")


if __name__ == "__main__":
    main()
