import numpy as np
from dataclasses import dataclass, field, asdict
from typing import Any, Mapping, ClassVar, Callable
import weakref
from types import MappingProxyType

from ..general import sort_line_indices  # , get_plane, get_tangent
from ..logging_decorator import logging_and_warning_decorator
from ..datatypes import (
    Vect,
    as_Vect,
    Tensor,
    as_Tensor,
    DefectIndex,
    as_DefectIndex,
    DimensionPeriodicInput,
    as_dimension_info,
    boundary_periodic_size_to_flag,
    as_str,
    as_Number,
    as_bool,
    UNSET,
    Unset,
)
from ..field import apply_linear_transform, unwrap_trajectory
from .visual.plot_figure import PlotFigure
from .visual.plot_tube import PlotTube, OptsTube
from .opts import merge_opts_all
from .smoothed_line import OptsSmooth, SmoothedLine
from ..general import pop_exclusive
from .class_base import ClassBase


# extra attr


@dataclass(slots=True)
class InputLine:
    defect_indices: DefectIndex | None = None
    box_size_periodic_index: DimensionPeriodicInput = False
    grid_offset: Vect(3) = (0, 0, 0)
    grid_transform: Tensor((3, 3)) = field(default_factory=lambda: np.eye(3))

    __descriptions__ = {
        "defect_indices": "indices of defect points in the Q array",
        "box_size_periodic_index": "the maximum index of each index in the Q array (finite values for periodic boundary conditions and np.inf for non-periodic)",
        "grid_offset": "grid translation offset to map lattice indices of Q array to real-space coordinates",
        "grid_transform": "grid transform matrix to map lattice indices of Q array to real-space coordinates (3x3)",
    }

    _validators = {
        "defect_indices": lambda v, d: (
            None if v is None else as_DefectIndex(v, is_return_row=True)
        ),
        "box_size_periodic_index": lambda v, d: as_dimension_info(v, name=d),
        "grid_offset": lambda v, d: as_Vect(v, name=d),
        "grid_transform": lambda v, d: as_Tensor(v, (3, 3), name=d),
    }

    def __setattr__(self, key, value):
        if key in self._validators:
            desc = f"{key!r}: {self.__class__.__descriptions__[key]}"
            value = self._validators[key](value, desc)
        object.__setattr__(self, key, value)


class DisclinationLine(ClassBase):

    __descriptions__ = {
        **(ClassBase.__descriptions__),
        # ========== user-facing ==========
        "raw_name": "Name identifier of this disclination line",
        # ========== raw (copied directly from InputLine or computed) ==========
        "_raw_defect_indices": "Lattice indices of defect points forming the line (array of shape N×3)",
        "_raw_box_size_periodic_index": "Box size along each dimension in index space (finite for periodic boundaries, np.inf for non-periodic)",
        "_raw_grid_offset": "Grid translation offset mapping lattice indices to real-space coordinates (3-vector)",
        "_raw_grid_transform": "Grid transformation matrix (3×3) mapping lattice indices to real-space coordinates",
        # ========== calc (derived quantities) ==========
        "_calc_end2end_kind": "kind of line ends: 'loop' (closed loop), 'cross' (wraps across boundary), or 'seg' (open segment)",
        "_calc_defect_num": "Number of defect points forming this line (integer)",
        "_calc_defect_coords": "Real-space coordinates of defect line (array of shape N×3)",
        "_calc_box_size_periodic_coord": "Box size expressed in real-space coordinates (3-vector, transformed from indices)",
        "_entity_smooth_objs": "DisclinationLineSmooth object generated by act_smooth (stores smoothing details)",
    }

    __slots__ = tuple(__descriptions__.keys())  # + ("__weakref__",)

    @logging_and_warning_decorator(start_finish_level=5)
    def __init__(
        self,
        inputValue: InputLine | None = None,
        is_sorted: bool = False,
        name: str | None = None,
        logger=None,
        **kwargs,
    ):

        if inputValue is None:
            inputValue = InputLine()

        super().__init__(name=name, name_replace="disclination line")

        inputValue = merge_opts_all({"": inputValue}, kwargs, type(self).__name__)[""]
        if inputValue.defect_indices is None:
            raise ValueError("No defects are input into disclination line")
        for k, v in asdict(inputValue).items():
            object.__setattr__(self, f"_raw_{k}", v)

        logger.detail(f"Initializing the disclination line {self.name!r}")

        if is_sorted == False:
            logger.detail("Sorting defects by closest neighboring pairs.")
            object.__setattr__(self, '_raw_defect_indices', sort_line_indices(self._raw_defect_indices))
        
        object.__setattr__(self, '_raw_box_size_periodic_index', as_dimension_info(self._raw_box_size_periodic_index))

        logger.debug("Classifying line kind by the distance between head and tail.")
        if (
            np.linalg.norm(self._raw_defect_indices[0] - self._raw_defect_indices[-1])
            == 0
        ):
            object.__setattr__(self, '_calc_end2end_kind', "loop")
            object.__setattr__(self, '_raw_defect_indices', self._raw_defect_indices[:-1])
        else:
            defect1 = self._raw_defect_indices[0].copy()
            defect2 = self._raw_defect_indices[-1].copy()
            defect1 = np.where(
                self._raw_box_size_periodic_index == np.inf,
                defect1,
                defect1 % self._raw_box_size_periodic_index,
            )
            defect2 = np.where(
                self._raw_box_size_periodic_index == np.inf,
                defect2,
                defect2 % self._raw_box_size_periodic_index,
            )
            if np.linalg.norm(defect1 - defect2) == 0:
                object.__setattr__(self, '_calc_end2end_kind', "cross")
                object.__setattr__(self, '_raw_defect_indices', self._raw_defect_indices[:-1])
            else:
                object.__setattr__(self, '_calc_end2end_kind', "seg")
                object.__setattr__(self, '_raw_defect_indices', self._raw_defect_indices)
        logger.debug(
            f"Disclination line {self.name!r} is of kind {self._calc_end2end_kind!r}"
        )
        logger.detail(
            f"The first and end point are {self._raw_defect_indices[0]} and {self._raw_defect_indices[-1]}"
        )

        object.__setattr__(self, '_calc_defect_num', np.shape(self._raw_defect_indices)[0])

        logger.detail("Calculating the defects positions in real-space units.")
        defect_coords = apply_linear_transform(
            self._raw_defect_indices,
            transform=self._raw_grid_transform,
            offset=self._raw_grid_offset,
        )
        object.__setattr__(self, "_calc_defect_coords", defect_coords)

        object.__setattr__(self, "_entity_smooth_objs", [])

    def act_smooth(
        self,
        is_new=False,
        opts: OptsSmooth | None = None,
        opts_defaults_override: Mapping[str, Any] | None = None,
        **kwargs,
    ):

        if not is_new and len(self.smooths) > 0:
            return

        name = self.name + " smooth_version " + str(len(self.smooths))

        item = DisclinationLineSmooth(
            self,
            name=name,
            opts=opts,
            opts_defaults_override=opts_defaults_override,
            **kwargs,
        )
        self.smooths.append(item)

        return item

    @logging_and_warning_decorator()
    def act_visualize(
        self,
        smooth_index: int = -1,
        figure: PlotFigure | None = None,
        is_wrap: bool = True,
        is_smooth: bool = True,
        opts: OptsTube | None = None,
        logger=None,
        **kwargs,
    ) -> None:

        if len(self.smooths) == 0:
            self.act_smooth(window_ratio=5)
            if is_smooth:
                logger.warning(
                    f"Currently there is no smoothed version of disclination line {self.name!r}"
                    "Plot the original points instead."
                )
                is_smooth = False

        try:
            smooth_obj = self.smooths[smooth_index]
        except Exception:
            logger.exception("Check input")
            logger.recovery("Use the latest version instead.")
            smooth_obj = self.smooths[-1]

        if getattr(smooth_obj, "_entity_visual", None):
            smooth_obj = self.act_smooth(is_new=True, opts=smooth_obj.opts)

        line_plot = smooth_obj.act_visualize(
            figure=figure, is_wrap=is_wrap, is_smooth=is_smooth, opts=opts, **kwargs
        )

        return line_plot

    def __len__(self) -> int:
        return self._calc_defect_num

    def __repr__(self) -> str:
        cls_name = self.__class__.__name__
        msg = f"{cls_name}(name={self.name!r}), has {self._calc_defect_num} defect points with type {self._calc_end2end_kind}"
        return msg

    def __iter__(self):
        return iter(self._raw_defect_indices)

    def __getitem__(self, idx):
        return self._raw_defect_indices[idx]

    def __array__(self, dtype=None):
        arr = self._raw_defect_indices
        return np.asarray(arr, dtype=dtype) if dtype is not None else arr

    @property
    def smooths(self):
        return getattr(self, "_entity_smooth_objs", None)

    @property
    def smooth(self):
        try:
            return self.smooths[-1]
        except:
            return

    @property
    def kind(self):
        return self._calc_end2end_kind


class DisclinationLineSmooth(SmoothedLine):

    __descriptions__ = {
        **SmoothedLine.__descriptions__,
        "_calc_result": "The smoothed disclination indices in lattice grid",
        "_calc_result_coords": "The smoothed disclination coords in real space",
        "_entity_visual": "The PlotTube object as the visualization of this smoothed disclination line",
        "_state_is_silhouette": "Whether to add silhouette when setting values of opts. Only used in control window.",
    }

    __slots__ = tuple(__descriptions__.keys())

    def __init__(
        self,
        line,
        opts: OptsSmooth | None = None,
        opts_defaults_override: Mapping[str, Any] | None = None,
        name: str | None = None,
        **kwargs,
    ):

        if not isinstance(line, DisclinationLine):
            raise TypeError(
                "The `line` input of DisclinationLineSmooth must be an instance of `DisclinationLine'"
                f"Got type={type(line).__name__} instead."
            )

        object.__setattr__(self, "_impl_owner_ref", weakref.ref(line))
        object.__setattr__(self, "_state_is_silhouette", True)

        if name is None:
            name = self.owner.name

        super().__init__(
            self.owner._raw_defect_indices,
            name=name,
            opts=opts,
            opts_defaults_override=opts_defaults_override,
            **kwargs,
        )

    def act_commit(self, opts: OptsSmooth | None = None, **kwargs):

        kwargs = self._helper_merge_opts_kwargs(opts=opts, **kwargs)
        self._helper_commit_apply_opts(**kwargs)

    @logging_and_warning_decorator()
    def _helper_commit_apply_opts(self, logger=None, **kwargs):

        v = kwargs.pop("mode", None)
        if v is not None:
            logger.warning(
                "'mode' is ignored and removed from kwargs because the smooth mode is determined by the kind of disclination line."
            )

        indices = self.owner._raw_defect_indices.copy()

        if self.owner._calc_end2end_kind == "loop":
            smooth_mode = "wrap"
            padding_num = 0

        elif self.owner._calc_end2end_kind == "cross":

            L = self.owner._raw_box_size_periodic_index

            if kwargs.get("window_ratio", None):
                padding_num = int(self._calc_N_init / kwargs["window_ratio"] / 2)
            else:
                padding_num = (
                    kwargs.get("window_length")
                    or self.opts.window_length
                    or self._calc_N_init
                )
                padding_num = int(padding_num / 2)

            logger.debug(
                f"line {self.name} is cross-kind. It has to deal with periodic boundary condition to smooth this line."
            )

            indices_origin = self.owner._raw_defect_indices.copy()
            tail = indices_origin[:padding_num].copy()
            head = indices_origin[-padding_num:].copy()
            indices = np.concatenate([head, indices_origin, tail])

            logger.detail("Start the whole unwrap.")
            indices = unwrap_trajectory(indices, box_size_periodic=L)

            logger.detail(
                "Shift the unwrapped line to the periodic image (mirror branch) which is closed to the original line."
            )
            start_origin = self.owner._raw_defect_indices[0]
            start_now = indices[padding_num]
            mask = np.isfinite(L)
            m = np.zeros(3, dtype=float)
            m[mask] = np.round((start_origin[mask] - start_now[mask]) / L[mask])
            shift_vec = m * L
            indices += shift_vec

            smooth_mode = "interp"
        else:
            smooth_mode = "interp"
            padding_num = 0

        object.__setattr__(self, "raw_coords", indices)

        super()._helper_commit_apply_opts(mode=smooth_mode, **kwargs)
        result = self._calc_result

        result = self._calc_result[
            int(padding_num * self.opts.N_out_ratio) : int(
                (-padding_num-1) * self.opts.N_out_ratio
            )
        ]
        object.__setattr__(self, "_calc_result", result)
        object.__setattr__(self, "_calc_N_out", len(result))

        result = apply_linear_transform(
            result,
            transform=self.owner._raw_grid_transform,
            offset=self.owner._raw_grid_offset,
        )
        object.__setattr__(self, "_calc_result_coords", result)

        tube = getattr(self, "_entity_visual", None)
        if tube:
            tube.act_commit(is_remesh=True, is_silhouette=self._state_is_silhouette)

    @logging_and_warning_decorator()
    def act_visualize(
        self,
        figure: PlotFigure | None = None,
        is_wrap: bool = True,
        is_smooth: bool = True,
        opts: OptsTube | None = None,
        opts_defaults_override: Mapping[str, Any] | None = None,
        logger=None,
        **kwargs,
    ):

        tube = DisclinationLineSmoothPlot(
            self,
            is_smooth=is_smooth,
            is_wrap=is_wrap,
            figure=figure,
            opts=opts,
            opts_defaults_override=opts_defaults_override,
            **kwargs,
        )

        object.__setattr__(self, "_entity_visual", tube)

        return tube


class DisclinationLineSmoothPlot:

    __descriptions__: ClassVar[Mapping[str, str]] = {
        "state_is_smooth": "Whether to apply geometric smoothing to defect lines during visualization.",
        "state_is_wrap": "Whether to apply periodic-boundary wrapping when visualizing defect lines.",
        "_entity": "The PlotTube instance as the visualization of the disclination line.",
        "_impl_sync_func": "Mapping from attribute names to synchronization callbacks.",
        "_impl_owner_ref": (
            "A weak reference to the owner object associated with this instance."
            "To access it, use .owner or ._impl_owner."
        ),
    }

    __slots__ = tuple(__descriptions__.keys()) + ("__weakref__",)

    _validators: ClassVar[Mapping[str, Callable[[Any, str], Any]]] = {
        "state_is_smooth": lambda v, d: as_bool(v, name=d),
        "state_is_wrap": lambda v, d: as_bool(v, name=d),
    }

    def __init__(
        self,
        line: DisclinationLineSmooth,
        is_smooth: bool = True,
        is_wrap: bool = True,
        figure: PlotFigure | None = None,
        opts: OptsTube | None = None,
        opts_defaults_override: Mapping[str, Any] | None = None,
        **kwargs,
    ):

        if not isinstance(line, DisclinationLineSmooth):
            raise TypeError(
                "The `line` input should be DisclinationLineSmooth instance."
                f"Got {type(line).__name__!r} instead"
            )
        object.__setattr__(self, "_impl_owner_ref", weakref.ref(line))

        is_smooth = as_bool(
            is_smooth,
            name="Whether to apply geometric smoothing to defect lines during visualization",
            replace=True,
        )
        object.__setattr__(self, "state_is_smooth", is_smooth)
        is_wrap = as_bool(
            is_wrap,
            name="Whether to apply periodic-boundary wrapping when visualizing defect lines",
            replace=True,
        )
        object.__setattr__(self, "state_is_wrap", is_wrap)

        line_coords, line_index = self._helper_get_coords()
        tube = PlotTube(
            coords=line_coords,
            name=self.owner.name,
            category="disclination line",
            figure=figure,
            opts=opts,
            line_index=line_index,
            opts_defaults_override=opts_defaults_override,
            **kwargs,
        )

        object.__setattr__(tube, "_impl_owner_ref", weakref.ref(self))
        object.__setattr__(self, "_entity", tube)

        sync_func = dict(state_is_smooth={}, state_is_wrap={})
        object.__setattr__(self, "_impl_sync_func", sync_func)

    @logging_and_warning_decorator(start_finish_level=5)
    def __setattr__(self, key, value, logger=None):

        if key in self.__class__._validators:
            desc = f"{key!r}: {self.__class__.__descriptions__[key]}"
            try:
                value = self.__class__._validators[key](value, desc)
            except Exception:
                logger.exception("Check input.")
                logger.recovery("Automatically ignore this modification.")
        else:
            raise AttributeError(
                f"{key!r} is not an editable attribute of DisclinationLineSmooth instance."
            )

        self.act_commit(**{key: value})

        sync_func = self._impl_sync_func.get(key, {})
        for func in sync_func.values():
            func()

    @property
    def owner(self):
        ref = self._impl_owner_ref
        return ref() if ref is not None else None

    _impl_owner = owner

    @logging_and_warning_decorator()
    def _helper_get_coords(self, logger=None):

        logger.debug(
            f"Start to visualize line: {self.owner.name!r} with kind ``{self.owner.owner._calc_end2end_kind}``"
        )

        if not self.state_is_wrap:

            line_coords = (
                self.owner._calc_result_coords
                if self.state_is_smooth
                else self.owner.owner._calc_defect_coords
            )
            if self.owner.owner._calc_end2end_kind == "loop":
                logger.detail(
                    f"Line {self.owner.name!r} is a loop. Closing the loop by appending the start point to the end."
                )
                line_coords = np.concatenate((line_coords, [line_coords[0]]))
            line_index = None

        else:

            logger.debug("Start to deal with the periodic boundary condition")

            boundary_flag = boundary_periodic_size_to_flag(
                self.owner.owner._raw_box_size_periodic_index
            )

            line_coords_origin = (
                self.owner.result
                if self.state_is_smooth
                else self.owner.owner._raw_defect_indices
            )
            if self.owner.owner._calc_end2end_kind == "loop":
                line_coords_origin = np.concatenate(
                    (line_coords_origin, [line_coords_origin[0]])
                )

            line_coords_origin = np.where(
                boundary_flag,
                line_coords_origin % self.owner.owner._raw_box_size_periodic_index,
                line_coords_origin,
            )

            logger.detail("Extracting the points at periodic boundaries.")
            diff = line_coords_origin[1:] - line_coords_origin[:-1]
            diff = np.linalg.norm(diff, axis=-1)
            end_list = np.where(diff > 1)[0] + 1
            end_list = np.concatenate([[0], end_list, [len(line_coords_origin)]])

            logger.detail(
                "Classifying the line into different segements due to periodic boundary conditions."
            )
            line_index = np.ones(len(line_coords_origin))
            for i in range(len(end_list) - 1):
                line_index[end_list[i] : end_list[i + 1]] = i

            line_coords = apply_linear_transform(
                line_coords_origin,
                transform=self.owner.owner._raw_grid_transform,
                offset=self.owner.owner._raw_grid_offset,
            )

        return line_coords, line_index

    @logging_and_warning_decorator(start_finish_level=5)
    def act_commit(
        self,
        opts: OptsTube = None,
        is_silhouette=True,
        is_remesh=False,
        logger=None,
        **kwargs,
    ):

        found, is_smooth, kwargs = pop_exclusive(kwargs, "is_smooth", "state_is_smooth")
        if found:
            try:
                is_smooth = as_bool(
                    is_smooth,
                    name="Whether to apply geometric smoothing to defect lines during visualization",
                )
                object.__setattr__(self, "state_is_smooth", is_smooth)
                is_remesh = True
            except Exception:
                logger.exception("Check input.")
                logger.recovery("Automatically ignore this modification.")

        found, is_wrap, kwargs = pop_exclusive(kwargs, "is_wrap", "state_is_wrap")
        if found:
            try:
                is_wrap = as_bool(
                    is_wrap,
                    name="Whether to apply periodic-boundary wrapping when visualizing defect lines",
                )
                object.__setattr__(self, "state_is_wrap", is_wrap)
                is_remesh = True
            except Exception:
                logger.exception("Check input.")
                logger.recovery("Automatically ignore this modification.")

        if is_remesh:
            line_coords, line_index = self._helper_get_coords()
            kwargs["coords"] = line_coords
            kwargs["line_index"] = line_index
        else:
            kwargs.pop("coords", None)
            kwargs.pop("line_index", None)
            
        self._entity.act_commit(opts=opts, is_silhouette=is_silhouette, **kwargs)
