import numpy as np
from dataclasses import dataclass, field, asdict
from typing import Any, Mapping, ClassVar, Callable
import weakref
from types import MappingProxyType

from ..general import sort_line_indices  # , get_plane, get_tangent
from ..logging_decorator import logging_and_warning_decorator
from ..datatypes import (
    Vect,
    as_Vect,
    Tensor,
    as_Tensor,
    DefectIndex,
    as_DefectIndex,
    DimensionPeriodicInput,
    as_dimension_info,
    boundary_periodic_size_to_flag,
    as_str,
    as_Number,
    as_bool,
    UNSET,
    Unset,
)
from ..field import apply_linear_transform, unwrap_trajectory
from .visual.plot_figure import PlotFigure
from .visual.plot_tube import PlotTube, OptsTube
from .opts import merge_opts_all, cover_value
from .smoothed_line import OptsSmooth, SmoothedLine
from ..general import pop_exclusive, find_plane_normal
from .class_base import ClassBase
from .host_base import OptsBase, HostBase
from .plane_grid_polar import OptsPlaneGridPolar, PlaneGridPolar
from .registry_base import RegistryBase
from .visual.qt.interact_disclination_line import InteractDisclinationLine


# extra attr


@dataclass(slots=True)
class InputLine:
    defect_indices: DefectIndex | None = None
    box_size_periodic_index: DimensionPeriodicInput = False
    grid_offset: Vect(3) = (0, 0, 0)
    grid_transform: Tensor((3, 3)) = field(default_factory=lambda: np.eye(3))

    __descriptions__ = {
        "defect_indices": "indices of defect points in the Q array",
        "box_size_periodic_index": "the maximum index of each index in the Q array (finite values for periodic boundary conditions and np.inf for non-periodic)",
        "grid_offset": "grid translation offset to map lattice indices of Q array to real-space coordinates",
        "grid_transform": "grid transform matrix to map lattice indices of Q array to real-space coordinates (3x3)",
    }

    _validators = {
        "defect_indices": lambda v, d: (
            None if v is None else as_DefectIndex(v, is_return_row=True)
        ),
        "box_size_periodic_index": lambda v, d: as_dimension_info(v, name=d),
        "grid_offset": lambda v, d: as_Vect(v, name=d),
        "grid_transform": lambda v, d: as_Tensor(v, (3, 3), name=d),
    }

    def __setattr__(self, key, value):
        if key in self._validators:
            desc = f"{key!r}: {self.__class__.__descriptions__[key]}"
            value = self._validators[key](value, desc)
        object.__setattr__(self, key, value)


class DisclinationLine(ClassBase):

    __descriptions__ = {
        **(ClassBase.__descriptions__),
        
        # ========== user-facing ==========
        "raw_name":                         "Name identifier of this disclination line",
        
        # ========== raw (copied directly from InputLine or computed) ==========
        "_raw_defect_indices":              "Lattice indices of defect points forming the line (array of shape Nx3)",
        "_raw_box_size_periodic_index":     "Box size along each dimension in index space (finite for periodic boundaries, np.inf for non-periodic)",
        "_raw_grid_offset":                 "Grid translation offset mapping lattice indices to real-space coordinates (3-vector)",
        "_raw_grid_transform":              "Grid transformation matrix (3x3) mapping lattice indices to real-space coordinates",
        
        # ========== derived quantities ==========
        "_calc_end2end_kind":               "kind of line ends: 'loop' (closed loop), 'cross' (wraps across boundary), or 'seg' (open segment)",
        "_calc_defect_num":                 "Number of defect points forming this line (integer)",
        "_calc_defect_coords":              "Real-space coordinates of defect line (array of shape Nx3)",
        "_calc_box_size_periodic_coord":    "Box size expressed in real-space coordinates (3-vector, transformed from indices)",
        "_calc_norm":                       "Estimated average plane normal vector of the disclination line (3-vector)",
        "_calc_norm_metric":                "A collection of confidence scores for the plane-fitting result",
        "_entity_smooth_objs":              "DisclinationLineSmooth object generated by act_smooth (stores smoothing details)",
    }

    __slots__ = tuple(
            k for k, v in __descriptions__.items() 
            if not v.startswith("Property:") and k not in ClassBase.__slots__
        )

    @logging_and_warning_decorator(start_finish_level=5)
    def __init__(
        self,
        inputValue: InputLine | None = None,
        is_sorted: bool = False,
        name: str | None = None,
        logger=None,
        **kwargs,
    ):

        if inputValue is None:
            inputValue = InputLine()

        super().__init__(name=name, name_replace="disclination line")

        inputValue = merge_opts_all({"": inputValue}, kwargs, type(self).__name__)[""]
        if inputValue.defect_indices is None:
            raise ValueError("No defects are input into disclination line")
        for k, v in asdict(inputValue).items():
            object.__setattr__(self, f"_raw_{k}", v)

        logger.detail(f"Initializing the disclination line {self.name!r}")

        if is_sorted == False:
            logger.detail("Sorting defects by closest neighboring pairs.")
            object.__setattr__(self, '_raw_defect_indices', sort_line_indices(self._raw_defect_indices))
        
        object.__setattr__(self, '_raw_box_size_periodic_index', as_dimension_info(self._raw_box_size_periodic_index))

        logger.debug("Classifying line kind by the distance between head and tail.")
        if (
            np.linalg.norm(self._raw_defect_indices[0] - self._raw_defect_indices[-1])
            == 0
        ):
            object.__setattr__(self, '_calc_end2end_kind', "loop")
            object.__setattr__(self, '_raw_defect_indices', self._raw_defect_indices[:-1])
        else:
            defect1 = self._raw_defect_indices[0].copy()
            defect2 = self._raw_defect_indices[-1].copy()
            defect1 = np.where(
                self._raw_box_size_periodic_index == np.inf,
                defect1,
                defect1 % self._raw_box_size_periodic_index,
            )
            defect2 = np.where(
                self._raw_box_size_periodic_index == np.inf,
                defect2,
                defect2 % self._raw_box_size_periodic_index,
            )
            if np.linalg.norm(defect1 - defect2) == 0:
                object.__setattr__(self, '_calc_end2end_kind', "cross")
                object.__setattr__(self, '_raw_defect_indices', self._raw_defect_indices[:-1])
            else:
                object.__setattr__(self, '_calc_end2end_kind', "seg")
                object.__setattr__(self, '_raw_defect_indices', self._raw_defect_indices)
        logger.debug(
            f"Disclination line {self.name!r} is of kind {self._calc_end2end_kind!r}"
        )
        logger.detail(
            f"The first and end point are {self._raw_defect_indices[0]} and {self._raw_defect_indices[-1]}"
        )

        object.__setattr__(self, '_calc_defect_num', np.shape(self._raw_defect_indices)[0])

        logger.detail("Calculating the defects positions in real-space units.")
        defect_coords = apply_linear_transform(
            self._raw_defect_indices,
            transform=self._raw_grid_transform,
            offset=self._raw_grid_offset,
        )
        object.__setattr__(self, "_calc_defect_coords", defect_coords)

        object.__setattr__(self, "_entity_smooth_objs", [])
        
        
    @logging_and_warning_decorator()
    def act_calc_norm(self, logger=None) -> np.ndarray:

        normal, metric = find_plane_normal(self._calc_defect_coords, is_return_metric=True)
        
        if metric["linearity_risk"] > 0.5:
            logger.warning(
                f"Low confidence in normal for {self.name!r}: "
                f"The disclination line is nearly straight. The calculated normal "
                f"may rotate arbitrarily around the line axis, "
                f"with linearity_risk as {metric['linearity_risk']:.2f}"
            )
            
        elif metric["planarity_score"] < 0.7:
            logger.warning(
                f"Low confidence in normal for {self.name!r}: "
                f"The line is highly non-planar (planarity_score={metric['planarity_score']:.2f}). "
                f"The result is only an 'average' plane normal."
            )
            
        object.__setattr__(self, "_calc_norm", normal)
        object.__setattr__(self, "_calc_norm_metric", metric)

        return normal
        
        

    def act_smooth(
        self,
        is_new=True,
        opts: OptsSmooth | None = None,
        opts_defaults_override: Mapping[str, Any] | None = None,
        **kwargs,
    ):

        if not is_new and len(self.smooths) > 0:
            return

        name = self.name + " smooth_version " + str(len(self.smooths))

        item = DisclinationLineSmooth(
            self,
            name=name,
            opts=opts,
            opts_defaults_override=opts_defaults_override,
            **kwargs,
        )
        self.smooths.append(item)

        return item

    @logging_and_warning_decorator()
    def act_visualize(
        self,
        smooth_index: int = -1,
        figure: PlotFigure | None = None,
        is_wrap: bool = True,
        is_smooth: bool = True,
        opts: OptsTube | None = None,
        logger=None,
        **kwargs,
    ) -> None:

        if len(self.smooths) == 0:
            self.act_smooth(window_length=5)
            if is_smooth:
                logger.warning(
                    f"Currently there is no smoothed version of disclination line {self.name!r}"
                    "Plot the original points instead."
                )
                is_smooth = False

        try:
            smooth_obj = self.smooths[smooth_index]
        except Exception:
            logger.exception("Check input")
            logger.recovery("Use the latest version instead.")
            smooth_obj = self.smooths[-1]

        if getattr(smooth_obj, "_entity_visual", None):
            smooth_obj = self.act_smooth(is_new=True, opts=smooth_obj.opts)

        line_plot = smooth_obj.act_visualize(
            figure=figure, is_wrap=is_wrap, is_smooth=is_smooth, opts_tube=opts, **kwargs
        )
        
        return line_plot

    def __len__(self) -> int:
        return self._calc_defect_num

    def __repr__(self) -> str:
        cls_name = self.__class__.__name__
        msg = f"{cls_name}({self.name!r}), type {self._calc_end2end_kind}, {self._calc_defect_num} defect points"
        return msg

    def __iter__(self):
        return iter(self._raw_defect_indices)

    def __getitem__(self, idx):
        return self._raw_defect_indices[idx]

    def __array__(self, dtype=None):
        arr = self._raw_defect_indices
        return np.asarray(arr, dtype=dtype) if dtype is not None else arr

    @property
    def smooths(self):
        return getattr(self, "_entity_smooth_objs", None)

    @property
    def smooth(self):
        try:
            return self.smooths[-1]
        except:
            return

    @property
    def kind(self):
        return self._calc_end2end_kind


class DisclinationLineSmooth(SmoothedLine):

    __descriptions__ = {
        **SmoothedLine.__descriptions__,
        "_calc_result": "The smoothed disclination indices in lattice grid",
        "_calc_result_coords": "The smoothed disclination coords in real space",
        "_entity_visual": "The PlotTube object as the visualization of this smoothed disclination line",
        "_entity_planes": "The DefectPlane objects as the cross-sections along the smoothed disclination line",
        "_calc_padding_num": "Temporary padding length used when smoothing a cross-boundary line.",
    }

    __slots__ = tuple(
            k for k, v in __descriptions__.items() 
            if not v.startswith("Property:") and k not in SmoothedLine.__slots__
        )

    # ==================== OVERRIDE ====================
    # DisclinationLineSmooth overrides SmoothedLine.__init__ because
    # it must bind a DisclinationLine owner and initialize the
    # defect-line-specific entities before the generic smoothing setup.
    # ==================================================
    def __init__(
        self,
        line,
        opts: OptsSmooth | None = None,
        opts_defaults_override: Mapping[str, Any] | None = None,
        name: str | None = None,
        **kwargs,
    ):

        if not isinstance(line, DisclinationLine):
            raise TypeError(
                "The `line` input of DisclinationLineSmooth must be an instance of `DisclinationLine'"
                f"Got type={type(line).__name__} instead."
            )

        object.__setattr__(self, "_impl_owner_ref", weakref.ref(line))
        object.__setattr__(self, "_entity_planes", RegistryBase(name="Planes"))
        object.__setattr__(self._entity_planes, "_impl_owner_ref", weakref.ref(self))
        object.__setattr__(self, "_state_is_silhouette", True)
        object.__setattr__(self, "_calc_padding_num", 0)

        if name is None:
            name = self.owner.name

        super().__init__(
            self.owner._raw_defect_indices,
            name=name,
            opts=opts,
            opts_defaults_override=opts_defaults_override,
            **kwargs,
        )

    # ==================== OVERRIDE ====================
    # DisclinationLineSmooth overrides SmoothedLine/HostBase pre-opts
    # handling to block external replacement of coords: this object
    # must always smooth the owner's defect coordinates.
    # ==================================================
    @logging_and_warning_decorator()
    def _helper_commit_pre_opts(self, kwargs, logger=None):
        found, _ = pop_exclusive(kwargs, "coords", "raw_coords")
        if found:
            logger.warning(
                "`coords` could not be modified because this object always smooths the owner defect coordinates."
            )
        return super()._helper_commit_pre_opts(kwargs)

    def _helper_resolve_coords(self):
        indices = self.owner._raw_defect_indices.copy()
        padding_num = 0
        smooth_mode = "interp"

        if self.owner._calc_end2end_kind == "loop":
            smooth_mode = "wrap"

        elif self.owner._calc_end2end_kind == "cross":
            L = self.owner._raw_box_size_periodic_index

            if self.opts.window_ratio is not None:
                padding_num = int(len(indices) / self.opts.window_ratio / 2)
            else:
                padding_num = int((self.opts.window_length or len(indices)) / 2)

            indices_origin = self.owner._raw_defect_indices.copy()
            tail = indices_origin[:padding_num].copy()
            head = indices_origin[-padding_num:].copy()
            indices = np.concatenate([head, indices_origin, tail])

            indices = unwrap_trajectory(indices, box_size_periodic=L)

            start_origin = self.owner._raw_defect_indices[0]
            start_now = indices[padding_num]
            mask = np.isfinite(L)
            m = np.zeros(3, dtype=float)
            m[mask] = np.round((start_origin[mask] - start_now[mask]) / L[mask])
            indices += m * L

        object.__setattr__(self, "_calc_padding_num", padding_num)
        object.__setattr__(self, "_calc_coords", indices)
        object.__setattr__(self.opts, "mode", smooth_mode)

    @logging_and_warning_decorator()
    def _helper_commit_apply_opts_main(self, is_reapply_opts=False, logger=None, **kwargs):
        if "mode" in kwargs:
            kwargs.pop("mode")
            logger.warning(
                "'mode' is ignored and removed from kwargs because the smooth mode is determined by the kind of disclination line."
            )

        super()._helper_commit_apply_opts_main(
            is_reapply_opts=is_reapply_opts,
            logger=logger,
            **kwargs,
        )

        padding_num = int(getattr(self, "_calc_padding_num", 0))
        if self._state_is_smoothed and padding_num > 0 and len(self._calc_result) > 0:
            trim = int(round(padding_num * float(self.opts.N_out_ratio)))
            if trim > 0 and (2 * trim) < len(self._calc_result):
                result = self._calc_result[trim:-trim]
                object.__setattr__(self, "_calc_result", result)
                object.__setattr__(self, "_calc_N_out", len(result))

        if not self._state_is_smoothed:
            object.__setattr__(self, "_calc_result", self.owner._raw_defect_indices.copy())
            object.__setattr__(self, "_calc_N_out", len(self._calc_result))

        result_coords = apply_linear_transform(
            self._calc_result,
            transform=self.owner._raw_grid_transform,
            offset=self.owner._raw_grid_offset,
        )
        object.__setattr__(self, "_calc_result_coords", result_coords)

        tube_wrapper = getattr(self, "_entity_visual", None)
        if tube_wrapper:
            tube_wrapper.act_commit()

    def act_visualize(
        self,
        figure: PlotFigure | None = None,
        is_wrap: bool = True,
        is_smooth: bool = True,
        opts: OptsTube | None = None,
        opts_defaults_override: Mapping[str, Any] | None = None,
        **kwargs,
    ):

        tube = DisclinationLineSmoothPlot(
            self,
            is_smooth=is_smooth,
            is_wrap=is_wrap,
            figure=figure,
            opts=opts,
            opts_defaults_override=opts_defaults_override,
            **kwargs,
        )

        object.__setattr__(self, "_entity_visual", tube)

        return tube
    
    def act_add_local_plane(self, x_param, **kwargs):
        plane = DefectPlane(self, x_param, **kwargs)
        return plane

@dataclass(slots=True, repr=False)
class OptsDefectLinePlot(OptsBase):

    is_smooth: bool | Unset = UNSET
    is_wrap: bool | Unset = UNSET

    __descriptions__: ClassVar[Mapping[str, str]] = {
        **OptsBase.__descriptions__,
        "is_smooth": "Whether to apply geometric smoothing to defect lines during visualization.",
        "is_wrap": "Whether to apply periodic-boundary wrapping when visualizing defect lines.",
    }

    _validators: ClassVar[Mapping[str, Callable[[Any, str], Any]]] = {
        **OptsBase._validators,
        "is_smooth": lambda v, d: as_bool(v, name=d),
        "is_wrap": lambda v, d: as_bool(v, name=d),
    }

    _DEFAULTS_FROZEN: ClassVar[Mapping[str, Any]] = MappingProxyType(
        {
            **dict(getattr(OptsBase, "_DEFAULTS_FROZEN", {})),
            "is_smooth": True,
            "is_wrap": True,
        }
    )


class DisclinationLineSmoothPlot(HostBase):

    __descriptions__: ClassVar[Mapping[str, str]] = {
        **HostBase.__descriptions__,
        "raw_name": "The name of this instance for visualization of defect line (smoothed/unsmoothed)"
    }

    __slots__ = tuple(
        k
        for k, v in __descriptions__.items()
        if not v.startswith("Property:") and k not in HostBase.__slots__
    )
    
    # ==================== OVERRIDE ====================
    # DisclinationLineSmoothPlot overrides HostBase.__init__ because
    # it must create and bind an internal PlotTube wrapped by this
    # visualization wrapper during initialization.
    # ==================================================
    @logging_and_warning_decorator(start_finish_level=5)
    def __init__(
        self,
        line: DisclinationLineSmooth,
        figure: PlotFigure | None = None,
        opts: OptsDefectLinePlot | None = None,
        opts_tube: OptsTube | None = None,
        opts_defaults_override: Mapping[str, Any] | None = None,
        opts_tube_defaults_override: Mapping[str, Any] | None = None,
        name: str | None = None,
        logger=None,
        **kwargs,
    ):

        if not isinstance(line, DisclinationLineSmooth):
            raise TypeError(
                "The `line` input should be DisclinationLineSmooth instance. "
                f"Got {type(line).__name__!r} instead"
            )
            
        self_descriptions = OptsDefectLinePlot.__descriptions__
        self_kwargs = {k: kwargs.pop(k) for k in list(kwargs.keys()) if k in self_descriptions}

        super().__init__(
            opts_type=OptsDefectLinePlot,
            opts=opts,
            opts_defaults_override=opts_defaults_override,
            name=line.name,
            name_replace="visualization of smoothed disclination line",
            **self_kwargs
        )

        object.__setattr__(self, "_impl_owner_ref", weakref.ref(line))

        self.opts.act_finalize(defaults=self._opts_defaults)

        line_coords, line_index = self._helper_get_coords()
        tube = PlotTube(
            coords=line_coords,
            name=self.owner.name,
            category="disclination line",
            figure=figure,
            opts=opts_tube,
            line_index=line_index,
            opts_defaults_override=opts_tube_defaults_override,
            **kwargs,
        )

        tube.act_bind_wrapper(self, protected_attrs=["coords", "line_index"])
        self.act_attach_enrich_kwargs_wrapped_task("visual_coords", self._helper_enrich_kwargs_wrapped_visual)
        tube.act_set_interact_func(lambda: InteractDisclinationLine(tube).show())


    @logging_and_warning_decorator()
    def _helper_get_coords(self, logger=None):

        is_smooth = bool(self.opts.is_smooth)
        is_wrap = bool(self.opts.is_wrap)
        owner = self.owner
        
        logger.debug(
            f"Start to visualize line: {owner.name!r} with kind ``{owner.owner._calc_end2end_kind}``"
        )

        if not is_wrap:

            line_coords = (
                owner._calc_result_coords
                if is_smooth
                else owner.owner._calc_defect_coords
            )
            if owner.owner._calc_end2end_kind == "loop":
                logger.detail(
                    f"Line {owner.name!r} is a loop. Closing the loop by appending the start point to the end."
                )
                line_coords = np.concatenate((line_coords, [line_coords[0]]))
            line_index = None

        else:

            logger.debug("Start to deal with the periodic boundary condition")

            boundary_flag = boundary_periodic_size_to_flag(
                owner.owner._raw_box_size_periodic_index
            )

            line_coords_origin = (
                owner.result
                if is_smooth
                else owner.owner._raw_defect_indices
            )
            if owner.owner._calc_end2end_kind == "loop":
                line_coords_origin = np.concatenate(
                    (line_coords_origin, [line_coords_origin[0]])
                )

            line_coords_origin = np.where(
                boundary_flag,
                line_coords_origin % owner.owner._raw_box_size_periodic_index,
                line_coords_origin,
            )

            logger.detail("Extracting the points at periodic boundaries.")
            diff = line_coords_origin[1:] - line_coords_origin[:-1]
            diff = np.linalg.norm(diff, axis=-1)
            end_list = np.where(diff > 1)[0] + 1
            end_list = np.concatenate([[0], end_list, [len(line_coords_origin)]])

            logger.detail(
                "Classifying the line into different segements due to periodic boundary conditions."
            )
            line_index = np.ones(len(line_coords_origin))
            for i in range(len(end_list) - 1):
                line_index[end_list[i] : end_list[i + 1]] = i

            line_coords = apply_linear_transform(
                line_coords_origin,
                transform=owner.owner._raw_grid_transform,
                offset=owner.owner._raw_grid_offset,
            )

        return line_coords, line_index
    
    def _helper_enrich_kwargs_wrapped_visual(self, host=None, kwargs=None):
        line_coords, line_index = self._helper_get_coords()
        return {"coords": line_coords, "line_index": line_index}


    @logging_and_warning_decorator()
    def _helper_commit_apply_opts_main(self, is_reapply_opts=False, logger=None, **kwargs):
        if not is_reapply_opts and not kwargs:
            return
        with self.opts._helper_internal_update():
            cover_value(
                self.opts,
                is_allow_cover_target_set=True,
                is_allow_unset_source=False,
                **kwargs,
            )


class DefectPlane(ClassBase):

    __descriptions__: ClassVar[Mapping[str, str]] = {
        **(ClassBase.__descriptions__),
        "x_param": "Continuous spline parameter along the curve", 
        "state_normal": "The plane normal, provided either as a key from 'const_normals' or as a direct vector.",
        "const_normals": "A mapping of named constant vectors for convenient reuse as plane normals.",
        "_entity": "The PlaneGridPolar instance as lattice grid surrounding the defect.",
        "_impl_sync_func": "Mapping from attribute names to synchronization callbacks.",
    }

    __slots__ = tuple(
        k
        for k, v in __descriptions__.items()
        if not v.startswith("Property:") and k not in ClassBase.__slots__
    )
    
    @logging_and_warning_decorator(start_finish_level=5)
    def __init__(
        self,
        line: DisclinationLineSmooth,
        x_param: float,
        name: str = "defect plane",
        name_replace: str = "defect plane",
        state_normal: Unset | Vect(3) = UNSET,
        const_normals: dict = {},
        opts: OptsPlaneGridPolar | None = None,
        opts_defaults_override: Mapping[str, Any] | None = None,
        logger=None,
        **kwargs,
    ):
        
        super().__init__(name=name, name_replace=name_replace)
        
        sync_func = dict(x_param={}, state_normal={})
        object.__setattr__(self, "_impl_sync_func", sync_func)

        if not isinstance(line, DisclinationLineSmooth):
            raise TypeError(
                "The `line` input should be DisclinationLineSmooth instance."
                f"Got {type(line).__name__!r} instead"
            )
        line._entity_planes.act_register(self)
        
        x_param = self._helper_check_x_param(x_param)
        object.__setattr__(self, "x_param", x_param)
        
        object.__setattr__(self, "const_normals", {})
        for key, value in const_normals.items():
            self.act_add_const_normal(key, value)
        
        state_normal = self._helper_check_state_normal(state_normal)
        object.__setattr__(self, 'state_normal', state_normal)
        
        normal, origin = self._helper_resolve()
        plane_polar = PlaneGridPolar(
            normal=normal,
            origin=origin,
            opts=opts,
            opts_defaults_override=opts_defaults_override
            )
        
        object.__setattr__(plane_polar, "_impl_owner_ref", weakref.ref(self))
        object.__setattr__(self, "_entity", plane_polar)
        
        
    def _helper_resolve(self):
        
        smooth = self.registry._impl_owner_ref()
        normal, origin = smooth.act_calc_tangent(self.x_param, is_return_coord=True)
        self.const_normals[UNSET] = normal
        
        if self.state_normal is not UNSET:
            normal = self.state_normal if not isinstance(self.state_normal, str) else self.const_normals[self.state_normal]
            
        return normal, origin
    
    @logging_and_warning_decorator(start_finish_level=5)
    def act_commit(
        self,
        opts: OptsPlaneGridPolar = None,
        logger=None,
        **kwargs,
    ):
        
        x_param = kwargs.get("x_param", None)
        if x_param:
            x_param = self._helper_check_x_param(x_param)
            object.__setattr__(self, "x_param", x_param)
            for func in self._impl_sync_func.get("x_param", {}).values():
                func()
            kwargs.pop("x_param")
        
        state_normal = kwargs.get("state_normal", None)
        if state_normal:
            state_normal = self._helper_check_state_normal(state_normal)
            object.__setattr__(self, "state_normal", state_normal)
            for func in self._impl_sync_func.get("state_normal", {}).values():
                func()
            kwargs.pop("state_normal")
            
        normal, origin = self._helper_resolve()
        kwargs["normal"] = normal
        kwargs["origin"] = origin
            
        self._entity.act_commit(opts=opts, **kwargs)


        
    def __setattr__(self, key, value):
        if key in self._impl_sync_func.keys():
            self.act_commit(**{key: value})
        else:
            super().__setattr__(key, value)
    
    @logging_and_warning_decorator(start_finish_level=5)
    def _helper_check_x_param(self, x_param, logger=None):
        x_param = as_Number(
            x_param,
            name="x_param: "+self.__descriptions__["x_param"], 
            value_range=(0,100)
            )
        return x_param
        
        
    @logging_and_warning_decorator(start_finish_level=5)
    def act_add_const_normal(self, key, value, logger=None):
        try:
            key = as_str(key)
            value = as_Vect(value, is_norm=True)
            self.const_normals[key] = value
        except Exception:
            logger.exception("Check input.")
            logger.recovery(
                f"Got key={key} and value={value} in `const_normals`.\n"
                "However, key must be string while value must be 3-element-vector.\n"
                "Automatically skip them."
            )

    @logging_and_warning_decorator(start_finish_level=5)
    def _helper_check_state_normal(self, state_normal, logger=None):
        try:
            if state_normal is UNSET:
                pass
            elif isinstance(state_normal, str):
                state_normal = as_str(
                    state_normal, 
                    name="state_normal",
                    pool=self.const_normals.keys()
                )
            else:
                state_normal = as_Vect(state_normal, is_norm=True)
        except Exception:
            logger.exception("Check input.")
            logger.recovery(
                f"Invalid `state_normal` provided: {state_normal!r}. "
                "Expected one of: 1) None (defaults to tangent), "
                "2) a valid key from `const_normals`, or "
                "3) a 3-element vector. "
                "Reverting `state_normal` to None."
            )
        return state_normal


