"""Geometry helpers used by disclination-line neighborhood analysis."""

import numpy as np


__all__ = ["get_square", "get_square_each"]


def get_square_each(size, num, dim=2):
    """Generate one square boundary with evenly spaced edge points.

    The boundary starts at the origin corner and traverses the four edges
    without duplicating corner points. In 3D mode, the square lies in the
    yz-plane with x = 0.
    """
    corners = np.array([[0, 0], [size, 0], [size, size], [0, size]])

    edges = []
    for i in range(4):
        p0, p1 = corners[i], corners[(i + 1) % 4]
        edges.append(np.linspace(p0, p1, num - 1, endpoint=False))
    coords = np.vstack(edges)

    if dim == 3:
        coords = np.hstack([np.zeros((coords.shape[0], 1)), coords])

    return coords


def get_square(size_list, num_list, origin_list=((0, 0, 0),), dim=3):
    """Generate and concatenate multiple square boundaries.

    Each square is generated by :func:`get_square_each` and translated by the
    corresponding origin. ``size_list``, ``num_list``, and ``origin_list`` must
    describe the same number of squares.
    """
    if np.isscalar(size_list):
        size_list = np.asarray([size_list])
    if np.isscalar(num_list):
        num_list = np.asarray([num_list])

    if not len(size_list) == len(num_list) == np.shape(origin_list)[0]:
        raise ValueError(
            "size_list, num_list, and origin_list must describe the same number "
            "of squares."
        )

    results = [
        get_square_each(size, num, dim) + origin
        for size, num, origin in zip(size_list, num_list, origin_list)
    ]
    return np.vstack(results)
