"""
Geometry helpers for vector parameterization, angle wrapping, and local frame conversions.
"""

from dataclasses import dataclass
from typing import ClassVar

import numpy as np
from scipy.spatial import ConvexHull, QhullError
from scipy.spatial.transform import Rotation as R

from ..core.result_base import ResultBase
from ..datatypes import Tensor, Vect, as_axes, as_dimension_info, as_points, as_vector


# ===========================================================================
# OBB fitting helpers
# ---------------------------------------------------------------------------
# This block supports approximate oriented bounding-box construction from
# point clouds: hull reduction, PCA initialization, random refinement, and the
# shared OBBFit result object.
# ===========================================================================


@dataclass(slots=True, frozen=True, repr=False)
class OBBFit(ResultBase):
    """Pure geometry result for an oriented bounding-box fit."""

    __result_name__: ClassVar[str] = "The parameters of an oriented bounding-box fit"

    axes: np.ndarray
    center: np.ndarray
    lengths: np.ndarray
    local_min: np.ndarray
    local_max: np.ndarray
    volume: float


def compute_convex_hull_points(points):
    """Return the unique convex-hull vertices of a 3D point cloud.

    Degenerate point clouds, such as coplanar or collinear points, do not have a
    full 3D convex hull under Qhull's default rules. For those cases, this
    helper falls back to the unique input points so downstream approximate OBB
    fitting can decide how to handle the lower-dimensional geometry.
    """

    points = as_points(
        points,
        name="points used to compute a convex hull",
        d=3,
        is_unique=True,
        min_num=1,
    )
    if len(points) <= 3:
        return points

    try:
        hull = ConvexHull(points)
    except QhullError:
        return points

    return points[np.unique(hull.vertices)]


def obb_fit_pca(points):
    """Fit a deterministic PCA-oriented bounding box to 3D points.

    The returned axes are stored as columns. The fit is not a guaranteed
    minimum-volume OBB; it is a fast, stable initial orientation for later
    refinement.
    """

    points = as_points(
        points,
        name="points used to fit a PCA oriented bounding box",
        d=3,
        is_unique=True,
        min_num=1,
    )

    centroid = np.mean(points, axis=0)
    centered_points = points - centroid
    covariance = centered_points.T @ centered_points / len(points)

    if np.allclose(covariance, 0.0):
        axes = np.eye(3)
    else:
        eigenvalues, eigenvectors = np.linalg.eigh(covariance)
        order = np.argsort(eigenvalues)[::-1]
        axes = eigenvectors[:, order]

    axes = canonicalize_axes(axes)
    return _obb_fit_in_axes(points, axes)


def obb_refine_random_search(
    points,
    initial_fit: OBBFit,
    *,
    angle_scales_deg=(15.0, 5.0, 1.0, 0.2),
    trials_per_scale=64,
    seed=None,
):
    """Refine an OBB fit by random multi-scale rotation search.

    This is an approximate stochastic optimizer, not an exact minimum-volume
    OBB solver. Candidate frames are generated by rotating the current best
    axes by random axis-angle perturbations. Only candidates with smaller box
    volume are accepted, so the returned fit is never worse than
    ``initial_fit`` under the sampled candidates.
    """

    points = as_points(
        points,
        name="points used to refine an oriented bounding box",
        d=3,
        is_unique=True,
        min_num=1,
    )
    if not isinstance(initial_fit, OBBFit):
        raise TypeError(
            "`initial_fit` must be an OBBFit returned by `obb_fit_pca` or "
            "another OBB fitting helper."
        )

    trials_per_scale = int(trials_per_scale)
    if trials_per_scale < 1:
        raise ValueError("`trials_per_scale` must be at least 1.")

    angle_scales_deg = np.asarray(angle_scales_deg, dtype=float)
    if angle_scales_deg.ndim != 1 or len(angle_scales_deg) == 0:
        raise ValueError("`angle_scales_deg` must be a non-empty 1D sequence.")
    if np.any(angle_scales_deg < 0):
        raise ValueError("`angle_scales_deg` cannot contain negative values.")

    rng = np.random.default_rng(seed)
    best_fit = initial_fit

    for angle_scale_deg in angle_scales_deg:
        angle_scale_rad = np.deg2rad(angle_scale_deg)
        for _ in range(trials_per_scale):
            rotvec = rng.normal(size=3)
            rotvec_norm = float(np.linalg.norm(rotvec))
            if rotvec_norm == 0.0 or angle_scale_rad == 0.0:
                continue

            rotvec *= rng.normal(scale=angle_scale_rad) / rotvec_norm
            rotation = R.from_rotvec(rotvec).as_matrix()
            candidate_axes = rotation @ best_fit.axes
            candidate_fit = _obb_fit_in_axes(points, candidate_axes)

            if candidate_fit.volume < best_fit.volume:
                best_fit = candidate_fit

    return best_fit


def obb_fit_approx(
    points,
    *,
    angle_scales_deg=(15.0, 5.0, 1.0, 0.2),
    trials_per_scale=64,
    seed=None,
):
    """Fit the repository's approximate minimum-volume OBB for 3D points.

    The current approximation pipeline reduces the input to convex-hull
    vertices, builds a deterministic PCA OBB, then refines that frame with a
    reproducible multi-scale random search.
    """

    hull_points = compute_convex_hull_points(points)
    initial_fit = obb_fit_pca(hull_points)
    return obb_refine_random_search(
        hull_points,
        initial_fit,
        angle_scales_deg=angle_scales_deg,
        trials_per_scale=trials_per_scale,
        seed=seed,
    )


def box_corners_from_center_axes_radii(center, axes, radii) -> np.ndarray:
    """Return orthogonal box corners from center, axes, and per-axis radii.

    ``axes`` is a ``(3, 3)`` orthonormal frame stored as column vectors.  The
    returned corners have shape ``(8, 3)``.
    """
    center = as_vector(center, name="box center", d=3)
    axes = as_axes(axes, name="box axes")
    radii = as_dimension_info(radii, name="box radii").astype(float)
    if np.any(radii <= 0):
        raise ValueError("`radii` must contain only positive values.")

    local_corners = np.array(
        [
            [-radii[0], -radii[1], -radii[2]],
            [radii[0], -radii[1], -radii[2]],
            [-radii[0], radii[1], -radii[2]],
            [-radii[0], -radii[1], radii[2]],
            [radii[0], radii[1], -radii[2]],
            [radii[0], -radii[1], radii[2]],
            [-radii[0], radii[1], radii[2]],
            [radii[0], radii[1], radii[2]],
        ],
        dtype=float,
    )
    return center + local_corners @ axes.T


def canonicalize_axes(axes):
    """Make a column-wise axes matrix deterministic and right-handed.

    Eigenvectors are sign-ambiguous: both ``v`` and ``-v`` describe the same
    axis. This helper fixes each axis sign by making its largest-magnitude
    component positive, then flips the final axis if needed so the full frame is
    right-handed.
    """

    axes = np.asarray(axes, dtype=float).copy()
    if axes.shape != (3, 3):
        raise ValueError(f"Expected axes to have shape (3, 3), got {axes.shape}.")

    for axis_index in range(3):
        axis = axes[:, axis_index]
        pivot = int(np.argmax(np.abs(axis)))
        if axis[pivot] < 0:
            axes[:, axis_index] = -axis

    if np.linalg.det(axes) < 0:
        axes[:, -1] = -axes[:, -1]

    return axes


def axes_angle_changes_deg(axes, reference_axes, *, is_unsigned: bool = True):
    """Return per-axis angle changes between two 3D orthonormal frames.

    The axes are compared column by column.  When ``is_unsigned`` is true,
    ``v`` and ``-v`` are treated as the same axis, which is useful for nematic
    axes and eigenvector frames with sign ambiguity.
    """

    axes = as_axes(axes, name="axes")
    reference_axes = as_axes(reference_axes, name="reference_axes")
    cosines = np.sum(axes * reference_axes, axis=0)
    if is_unsigned:
        cosines = np.abs(cosines)
    cosines = np.clip(cosines, -1.0, 1.0)
    return np.degrees(np.arccos(cosines))


def align_axes_to_reference(axes, reference_axes, *, is_right_handed: bool = True):
    """Flip axes signs column-wise to stay close to a reference frame.

    This handles the sign ambiguity of eigenvector frames and nematic axes.
    Each axis column is flipped when its dot product with the corresponding
    reference axis is negative.  When ``is_right_handed`` is true, the final
    axis is flipped if needed so the returned frame is right-handed.
    """

    axes = as_axes(axes, name="axes", is_right_handed=False)
    reference_axes = as_axes(
        reference_axes,
        name="reference_axes",
        is_right_handed=False,
    )

    dots = np.sum(axes * reference_axes, axis=0)
    signs = np.where(dots < 0, -1.0, 1.0)
    aligned_axes = axes * signs

    if is_right_handed and np.linalg.det(aligned_axes) < 0:
        aligned_axes[:, -1] = -aligned_axes[:, -1]

    return aligned_axes


def _obb_fit_in_axes(points, axes):
    """Return the smallest OBB fit wrapping points in the supplied axes."""

    points = as_points(
        points,
        name="points used to fit an oriented bounding box",
        d=3,
        min_num=1,
    )
    axes = canonicalize_axes(axes)

    local_points = points @ axes
    local_min = np.min(local_points, axis=0)
    local_max = np.max(local_points, axis=0)
    lengths = local_max - local_min
    local_center = 0.5 * (local_min + local_max)
    center = local_center @ axes.T
    volume = float(np.prod(lengths))

    return OBBFit(
        axes=axes,
        center=center,
        lengths=lengths,
        local_min=local_min,
        local_max=local_max,
        volume=volume,
    )


def calc_vec_from_azimuth_polar(azimuth, polar_angle):
    x = np.sin(polar_angle) * np.cos(azimuth)
    y = np.sin(polar_angle) * np.sin(azimuth)
    z = np.cos(polar_angle)
    return np.array((x, y, z), dtype=float)


def get_azimuth(vec):
    vec = np.asarray(vec, dtype=float)
    az_rad = np.arctan2(vec[1], vec[0])
    return np.degrees(az_rad) % 360


def get_polar_angle(vec):
    vec = np.asarray(vec, dtype=float).copy()
    vec /= np.linalg.norm(vec, axis=-1, keepdims=True)
    polar = np.arccos(vec[2])
    return np.degrees(polar)


def get_axis1_azimuth(axis1, normal):
    """
    Measure the azimuth of `axis1` in the local plane orthogonal to `normal`.

    The local reference frame is built by rotating the global z-axis onto
    `normal`, then taking the rotated global x/y axes as the in-plane basis.
    The returned angle is in degrees within ``[0, 360)``.
    """
    axis1 = np.asarray(axis1, dtype=float).copy()
    axis1 /= np.linalg.norm(axis1, axis=-1, keepdims=True)
    rotation = rotation_matrix_from_vectors((0, 0, 1), normal)
    axisx = rotation @ np.array([1.0, 0.0, 0.0])
    axisy = rotation @ np.array([0.0, 1.0, 0.0])
    az_rad = np.arctan2(axis1 @ axisy, axis1 @ axisx)
    return np.degrees(az_rad) % 360


def wrap_to_pi(angle):
    """Wrap angles in radians into the half-open interval ``[-pi, pi)``."""
    return (np.asarray(angle) + np.pi) % (2.0 * np.pi) - np.pi


def rotation_matrix_from_vectors(
    source_vector: Vect(3), target_vector: Vect(3)
) -> Tensor((3, 3)):
    """
    Construct a rotation matrix that rotates one vector to another.

    This function computes a 3x3 rotation matrix `R` such that:
        R @ source_vector ~= target_vector

    It internally uses SciPy's `Rotation.align_vectors` to find the
    minimal rotation that maps the source direction to the target
    direction.
    """
    source_vector = as_vector(
        source_vector,
        name="The vector used as the starting source when constructing the rotation matrix",
        is_normalized=True,
    )
    target_vector = as_vector(
        target_vector,
        name="The vector used as the ending target when constructing the rotation matrix",
        is_normalized=True,
    )

    rot, _ = R.align_vectors([target_vector], [source_vector])
    return rot.as_matrix()
