"""
Geometry helpers for vector parameterization, angle wrapping, and local frame conversions.
"""

from dataclasses import dataclass
from typing import ClassVar

import numpy as np
from scipy.spatial import ConvexHull, QhullError
from scipy.spatial.transform import Rotation as R

from .classes.result_base import ResultBase
from .datatypes import Tensor, Vect, as_Vect, as_points


@dataclass(slots=True, frozen=True, repr=False)
class OBBFit(ResultBase):
    """Pure geometry result for an oriented bounding-box fit."""

    __result_name__: ClassVar[str] = "The parameters of an oriented bounding-box fit"

    axes: np.ndarray
    center: np.ndarray
    lengths: np.ndarray
    local_min: np.ndarray
    local_max: np.ndarray
    volume: float


def compute_convex_hull_points(points):
    """Return the unique convex-hull vertices of a 3D point cloud.

    Degenerate point clouds, such as coplanar or collinear points, do not have a
    full 3D convex hull under Qhull's default rules. For those cases, this
    helper falls back to the unique input points so downstream approximate OBB
    fitting can decide how to handle the lower-dimensional geometry.
    """

    points = as_points(
        points,
        name="points used to compute a convex hull",
        dim=3,
        is_unique=True,
        min_num=1,
    )
    if len(points) <= 3:
        return points

    try:
        hull = ConvexHull(points)
    except QhullError:
        return points

    return points[np.unique(hull.vertices)]


def fit_obb_pca(points):
    """Fit a deterministic PCA-oriented bounding box to 3D points.

    The returned axes are stored as columns. The fit is not a guaranteed
    minimum-volume OBB; it is a fast, stable initial orientation for later
    refinement.
    """

    points = as_points(
        points,
        name="points used to fit a PCA oriented bounding box",
        dim=3,
        is_unique=True,
        min_num=1,
    )

    centroid = np.mean(points, axis=0)
    centered_points = points - centroid
    covariance = centered_points.T @ centered_points / len(points)

    if np.allclose(covariance, 0.0):
        axes = np.eye(3)
    else:
        eigenvalues, eigenvectors = np.linalg.eigh(covariance)
        order = np.argsort(eigenvalues)[::-1]
        axes = eigenvectors[:, order]

    axes = canonicalize_axes(axes)
    return _fit_obb_in_axes(points, axes)


def refine_obb_random_search(
    points,
    initial_fit: OBBFit,
    *,
    angle_scales_deg=(15.0, 5.0, 1.0, 0.2),
    trials_per_scale=64,
    seed=None,
):
    """Refine an OBB fit by random multi-scale rotation search.

    This is an approximate stochastic optimizer, not an exact minimum-volume
    OBB solver. Candidate frames are generated by rotating the current best
    axes by random axis-angle perturbations. Only candidates with smaller box
    volume are accepted, so the returned fit is never worse than
    ``initial_fit`` under the sampled candidates.
    """

    points = as_points(
        points,
        name="points used to refine an oriented bounding box",
        dim=3,
        is_unique=True,
        min_num=1,
    )
    if not isinstance(initial_fit, OBBFit):
        raise TypeError(
            "`initial_fit` must be an OBBFit returned by `fit_obb_pca` or "
            "another OBB fitting helper."
        )

    trials_per_scale = int(trials_per_scale)
    if trials_per_scale < 1:
        raise ValueError("`trials_per_scale` must be at least 1.")

    angle_scales_deg = np.asarray(angle_scales_deg, dtype=float)
    if angle_scales_deg.ndim != 1 or len(angle_scales_deg) == 0:
        raise ValueError("`angle_scales_deg` must be a non-empty 1D sequence.")
    if np.any(angle_scales_deg < 0):
        raise ValueError("`angle_scales_deg` cannot contain negative values.")

    rng = np.random.default_rng(seed)
    best_fit = initial_fit

    for angle_scale_deg in angle_scales_deg:
        angle_scale_rad = np.deg2rad(angle_scale_deg)
        for _ in range(trials_per_scale):
            rotvec = rng.normal(size=3)
            rotvec_norm = float(np.linalg.norm(rotvec))
            if rotvec_norm == 0.0 or angle_scale_rad == 0.0:
                continue

            rotvec *= rng.normal(scale=angle_scale_rad) / rotvec_norm
            rotation = R.from_rotvec(rotvec).as_matrix()
            candidate_axes = rotation @ best_fit.axes
            candidate_fit = _fit_obb_in_axes(points, candidate_axes)

            if candidate_fit.volume < best_fit.volume:
                best_fit = candidate_fit

    return best_fit


def canonicalize_axes(axes):
    """Make a column-wise axes matrix deterministic and right-handed.

    Eigenvectors are sign-ambiguous: both ``v`` and ``-v`` describe the same
    axis. This helper fixes each axis sign by making its largest-magnitude
    component positive, then flips the final axis if needed so the full frame is
    right-handed.
    """

    axes = np.asarray(axes, dtype=float).copy()
    if axes.shape != (3, 3):
        raise ValueError(f"Expected axes to have shape (3, 3), got {axes.shape}.")

    for axis_index in range(3):
        axis = axes[:, axis_index]
        pivot = int(np.argmax(np.abs(axis)))
        if axis[pivot] < 0:
            axes[:, axis_index] = -axis

    if np.linalg.det(axes) < 0:
        axes[:, -1] = -axes[:, -1]

    return axes


def _fit_obb_in_axes(points, axes):
    """Return the smallest OBB fit wrapping points in the supplied axes."""

    points = as_points(
        points,
        name="points used to fit an oriented bounding box",
        dim=3,
        min_num=1,
    )
    axes = canonicalize_axes(axes)

    local_points = points @ axes
    local_min = np.min(local_points, axis=0)
    local_max = np.max(local_points, axis=0)
    lengths = local_max - local_min
    local_center = 0.5 * (local_min + local_max)
    center = local_center @ axes.T
    volume = float(np.prod(lengths))

    return OBBFit(
        axes=axes,
        center=center,
        lengths=lengths,
        local_min=local_min,
        local_max=local_max,
        volume=volume,
    )


def calc_vec_from_azimuth_polar(azimuth, polar_angle):
    x = np.sin(polar_angle) * np.cos(azimuth)
    y = np.sin(polar_angle) * np.sin(azimuth)
    z = np.cos(polar_angle)
    return np.array((x, y, z), dtype=float)


def get_azimuth(vec):
    vec = np.asarray(vec, dtype=float)
    az_rad = np.arctan2(vec[1], vec[0])
    return np.degrees(az_rad) % 360


def get_polar_angle(vec):
    vec = np.asarray(vec, dtype=float).copy()
    vec /= np.linalg.norm(vec, axis=-1, keepdims=True)
    polar = np.arccos(vec[2])
    return np.degrees(polar)


def get_axis1_azimuth(axis1, normal):
    """
    Measure the azimuth of `axis1` in the local plane orthogonal to `normal`.

    The local reference frame is built by rotating the global z-axis onto
    `normal`, then taking the rotated global x/y axes as the in-plane basis.
    The returned angle is in degrees within ``[0, 360)``.
    """
    axis1 = np.asarray(axis1, dtype=float).copy()
    axis1 /= np.linalg.norm(axis1, axis=-1, keepdims=True)
    rotation = rotation_matrix_from_vectors((0, 0, 1), normal)
    axisx = rotation @ np.array([1.0, 0.0, 0.0])
    axisy = rotation @ np.array([0.0, 1.0, 0.0])
    az_rad = np.arctan2(axis1 @ axisy, axis1 @ axisx)
    return np.degrees(az_rad) % 360


def wrap_to_pi(angle):
    """Wrap angles in radians into the half-open interval ``[-pi, pi)``."""
    return (np.asarray(angle) + np.pi) % (2.0 * np.pi) - np.pi


def rotation_matrix_from_vectors(
    source_vector: Vect(3), target_vector: Vect(3)
) -> Tensor((3, 3)):
    """
    Construct a rotation matrix that rotates one vector to another.

    This function computes a 3x3 rotation matrix `R` such that:
        R @ source_vector ~= target_vector

    It internally uses SciPy's `Rotation.align_vectors` to find the
    minimal rotation that maps the source direction to the target
    direction.
    """
    source_vector = as_Vect(
        source_vector,
        name="The vector used as the starting source when constructing the rotation matrix",
        is_norm=True,
    )
    target_vector = as_Vect(
        target_vector,
        name="The vector used as the ending target when constructing the rotation matrix",
        is_norm=True,
    )

    rot, _ = R.align_vectors([target_vector], [source_vector])
    return rot.as_matrix()


def find_rotation_axis(directors, is_return_metric=False):
    """
    Find the common rotation axis for a sequence of normalized vectors.
    """
    M = np.dot(directors.T, directors)
    eigenvalues, eigenvectors = np.linalg.eigh(M)
    axis = eigenvectors[:, 0]

    cross_prods = np.cross(directors[:-1], directors[1:])
    avg_cross = np.sum(cross_prods, axis=0)

    if np.dot(axis, avg_cross) < 0:
        axis = -axis

    if not is_return_metric:
        return axis

    total_var = np.sum(eigenvalues)
    orthogonality_score = 1.0 - (eigenvalues[0] / total_var)
    rms_sin_theta = np.sqrt(eigenvalues[0] / len(directors))
    tilt_angle_deg = np.degrees(np.arcsin(np.clip(rms_sin_theta, -1.0, 1.0)))

    signed_rotation_steps = np.dot(cross_prods, axis)
    total_signed_rotation = np.sum(signed_rotation_steps)
    total_rotation_magnitude = np.sum(np.abs(signed_rotation_steps))
    rotation_consistency = (
        np.abs(total_signed_rotation) / total_rotation_magnitude
        if total_rotation_magnitude > 1e-12
        else 0.0
    )

    metric = {
        "orthogonality_score": orthogonality_score,
        "rms_sin_theta": rms_sin_theta,
        "tilt_angle_degrees": tilt_angle_deg,
        "rotation_consistency": rotation_consistency,
        "eigenvalues": eigenvalues,
    }
    return axis, metric


def find_plane_normal(points, is_return_metric=False):
    """
    Estimate the normal vector of a point cloud and evaluate its planarity.
    """
    if len(points) < 3:
        raise ValueError("At least 3 points are required to define a plane.")

    centroid = np.mean(points, axis=0)
    centered_points = points - centroid
    M = np.dot(centered_points.T, centered_points)
    eigenvalues, eigenvectors = np.linalg.eigh(M)
    normal = eigenvectors[:, 0]

    if not is_return_metric:
        return normal

    total_variance = np.sum(eigenvalues)
    planarity = (
        1.0 - (3.0 * eigenvalues[0] / total_variance) if total_variance > 0 else 1.0
    )
    thickness_rms = np.sqrt(eigenvalues[0] / len(points))
    linearity_risk = eigenvalues[0] / eigenvalues[1] if eigenvalues[1] > 1e-9 else 1.0

    metric = {
        "centroid": centroid,
        "planarity_score": np.clip(planarity, 0, 1),
        "thickness_rms": thickness_rms,
        "eigenvalues": eigenvalues,
        "linearity_risk": linearity_risk,
    }
    return normal, metric
